-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 17:21:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tododb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tododb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tododb` DEFAULT CHARACTER SET utf8mb3 ;
USE `tododb` ;

-- -----------------------------------------------------
-- Table `tododb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tododb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tododb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tododb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '게시물 고유 ID',
  `title` VARCHAR(255) NOT NULL COMMENT '제목',
  `content` TEXT NOT NULL COMMENT '내용',
  `user_id` INT NOT NULL COMMENT '작성자 User ID',
  `views` INT NULL DEFAULT '0' COMMENT '조회수',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일시',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `type` ENUM('notice', 'free') NULL DEFAULT 'free' COMMENT '게시물 타입',
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tododb`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '자유 게시판 게시물';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
